/*
 * TileDB Storage Platform API
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 2.17.51
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tiledb.cloud.rest_api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.tiledb.cloud.rest_api.model.AssetBackingType;
import io.tiledb.cloud.rest_api.model.AssetOwnershipLevel;
import io.tiledb.cloud.rest_api.model.AssetType;
import io.tiledb.cloud.rest_api.model.MetadataStringified;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AssetInfo
 */
public class AssetInfoTest {
    private final AssetInfo model = new AssetInfo();

    /**
     * Model tests for AssetInfo
     */
    @Test
    public void testAssetInfo() {
        // TODO: test AssetInfo
    }

    /**
     * Test the property 'uuid'
     */
    @Test
    public void uuidTest() {
        // TODO: test uuid
    }

    /**
     * Test the property 'assetType'
     */
    @Test
    public void assetTypeTest() {
        // TODO: test assetType
    }

    /**
     * Test the property 'assetBackingType'
     */
    @Test
    public void assetBackingTypeTest() {
        // TODO: test assetBackingType
    }

    /**
     * Test the property 'assetOwnershipLevel'
     */
    @Test
    public void assetOwnershipLevelTest() {
        // TODO: test assetOwnershipLevel
    }

    /**
     * Test the property 'namespaceName'
     */
    @Test
    public void namespaceNameTest() {
        // TODO: test namespaceName
    }

    /**
     * Test the property 'namespaceUuid'
     */
    @Test
    public void namespaceUuidTest() {
        // TODO: test namespaceUuid
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'mimeType'
     */
    @Test
    public void mimeTypeTest() {
        // TODO: test mimeType
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

}
