/*
 * TileDB Storage Platform API
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 2.17.51
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tiledb.cloud.rest_api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.tiledb.cloud.rest_api.model.StorageLocation;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AssetLocations
 */
public class AssetLocationsTest {
    private final AssetLocations model = new AssetLocations();

    /**
     * Model tests for AssetLocations
     */
    @Test
    public void testAssetLocations() {
        // TODO: test AssetLocations
    }

    /**
     * Test the property 'arrays'
     */
    @Test
    public void arraysTest() {
        // TODO: test arrays
    }

    /**
     * Test the property 'files'
     */
    @Test
    public void filesTest() {
        // TODO: test files
    }

    /**
     * Test the property 'groups'
     */
    @Test
    public void groupsTest() {
        // TODO: test groups
    }

    /**
     * Test the property 'mlModels'
     */
    @Test
    public void mlModelsTest() {
        // TODO: test mlModels
    }

    /**
     * Test the property 'notebooks'
     */
    @Test
    public void notebooksTest() {
        // TODO: test notebooks
    }

    /**
     * Test the property 'taskGraphs'
     */
    @Test
    public void taskGraphsTest() {
        // TODO: test taskGraphs
    }

    /**
     * Test the property 'udfs'
     */
    @Test
    public void udfsTest() {
        // TODO: test udfs
    }

}
