/*
 * TileDB Storage Platform API
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 2.2.19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tiledb.cloud.rest_api.model;

import org.junit.Test;


/**
 * Model tests for DomainArray
 */
public class DomainArrayTest {
    private final DomainArray model = new DomainArray();

    /**
     * Model tests for DomainArray
     */
    @Test
    public void testDomainArray() {
        // TODO: test DomainArray
    }

    /**
     * Test the property 'int8'
     */
    @Test
    public void int8Test() {
        // TODO: test int8
    }

    /**
     * Test the property 'uint8'
     */
    @Test
    public void uint8Test() {
        // TODO: test uint8
    }

    /**
     * Test the property 'int16'
     */
    @Test
    public void int16Test() {
        // TODO: test int16
    }

    /**
     * Test the property 'uint16'
     */
    @Test
    public void uint16Test() {
        // TODO: test uint16
    }

    /**
     * Test the property 'int32'
     */
    @Test
    public void int32Test() {
        // TODO: test int32
    }

    /**
     * Test the property 'uint32'
     */
    @Test
    public void uint32Test() {
        // TODO: test uint32
    }

    /**
     * Test the property 'int64'
     */
    @Test
    public void int64Test() {
        // TODO: test int64
    }

    /**
     * Test the property 'uint64'
     */
    @Test
    public void uint64Test() {
        // TODO: test uint64
    }

    /**
     * Test the property 'float32'
     */
    @Test
    public void float32Test() {
        // TODO: test float32
    }

    /**
     * Test the property 'float64'
     */
    @Test
    public void float64Test() {
        // TODO: test float64
    }

}
