/*
 * TileDB Storage Platform API
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 2.2.19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tiledb.cloud.rest_api.model;

import org.junit.Test;


/**
 * Model tests for FileExport
 */
public class FileExportTest {
    private final FileExport model = new FileExport();

    /**
     * Model tests for FileExport
     */
    @Test
    public void testFileExport() {
        // TODO: test FileExport
    }

    /**
     * Test the property 'outputUri'
     */
    @Test
    public void outputUriTest() {
        // TODO: test outputUri
    }

}
