/*
 * TileDB Storage Platform API
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 2.17.51
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tiledb.cloud.rest_api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.tiledb.cloud.rest_api.model.ArrayActions;
import io.tiledb.cloud.rest_api.model.GroupActions;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for InvitationGroupShareEmail
 */
public class InvitationGroupShareEmailTest {
    private final InvitationGroupShareEmail model = new InvitationGroupShareEmail();

    /**
     * Model tests for InvitationGroupShareEmail
     */
    @Test
    public void testInvitationGroupShareEmail() {
        // TODO: test InvitationGroupShareEmail
    }

    /**
     * Test the property 'arrayActions'
     */
    @Test
    public void arrayActionsTest() {
        // TODO: test arrayActions
    }

    /**
     * Test the property 'groupActions'
     */
    @Test
    public void groupActionsTest() {
        // TODO: test groupActions
    }

    /**
     * Test the property 'inviteeEmailOrName'
     */
    @Test
    public void inviteeEmailOrNameTest() {
        // TODO: test inviteeEmailOrName
    }

}
