/*
 * TileDB Storage Platform API
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 2.2.19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tiledb.cloud.rest_api.model;

import org.junit.Test;


/**
 * Model tests for LastAccessedArray
 */
public class LastAccessedArrayTest {
    private final LastAccessedArray model = new LastAccessedArray();

    /**
     * Model tests for LastAccessedArray
     */
    @Test
    public void testLastAccessedArray() {
        // TODO: test LastAccessedArray
    }

    /**
     * Test the property 'arrayId'
     */
    @Test
    public void arrayIdTest() {
        // TODO: test arrayId
    }

    /**
     * Test the property 'arrayName'
     */
    @Test
    public void arrayNameTest() {
        // TODO: test arrayName
    }

    /**
     * Test the property 'namespace'
     */
    @Test
    public void namespaceTest() {
        // TODO: test namespace
    }

    /**
     * Test the property 'accessedTime'
     */
    @Test
    public void accessedTimeTest() {
        // TODO: test accessedTime
    }

    /**
     * Test the property 'accessType'
     */
    @Test
    public void accessTypeTest() {
        // TODO: test accessType
    }

}
