/*
 * TileDB Storage Platform API
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 2.17.51
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tiledb.cloud.rest_api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.tiledb.cloud.rest_api.model.ArrayInfo;
import io.tiledb.cloud.rest_api.model.PaginationMetadata;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MLModelFavoritesData
 */
public class MLModelFavoritesDataTest {
    private final MLModelFavoritesData model = new MLModelFavoritesData();

    /**
     * Model tests for MLModelFavoritesData
     */
    @Test
    public void testMLModelFavoritesData() {
        // TODO: test MLModelFavoritesData
    }

    /**
     * Test the property 'mlmodels'
     */
    @Test
    public void mlmodelsTest() {
        // TODO: test mlmodels
    }

    /**
     * Test the property 'paginationMetadata'
     */
    @Test
    public void paginationMetadataTest() {
        // TODO: test paginationMetadata
    }

}
