/*
 * TileDB Storage Platform API
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 2.17.51
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tiledb.cloud.rest_api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.tiledb.cloud.rest_api.model.AssetLocations;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OrganizationUpdate
 */
public class OrganizationUpdateTest {
    private final OrganizationUpdate model = new OrganizationUpdate();

    /**
     * Model tests for OrganizationUpdate
     */
    @Test
    public void testOrganizationUpdate() {
        // TODO: test OrganizationUpdate
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'logo'
     */
    @Test
    public void logoTest() {
        // TODO: test logo
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'defaultS3Path'
     */
    @Test
    public void defaultS3PathTest() {
        // TODO: test defaultS3Path
    }

    /**
     * Test the property 'defaultS3PathCredentialsName'
     */
    @Test
    public void defaultS3PathCredentialsNameTest() {
        // TODO: test defaultS3PathCredentialsName
    }

    /**
     * Test the property 'assetLocations'
     */
    @Test
    public void assetLocationsTest() {
        // TODO: test assetLocations
    }

}
