/*
 * TileDB Storage Platform API
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 2.2.19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tiledb.cloud.rest_api.model;

import org.junit.Test;


/**
 * Model tests for SubarrayRanges
 */
public class SubarrayRangesTest {
    private final SubarrayRanges model = new SubarrayRanges();

    /**
     * Model tests for SubarrayRanges
     */
    @Test
    public void testSubarrayRanges() {
        // TODO: test SubarrayRanges
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'hasDefaultRange'
     */
    @Test
    public void hasDefaultRangeTest() {
        // TODO: test hasDefaultRange
    }

    /**
     * Test the property 'buffer'
     */
    @Test
    public void bufferTest() {
        // TODO: test buffer
    }

}
