/*
 * TileDB Storage Platform API
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 2.2.19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tiledb.cloud.rest_api.model;

import org.junit.Test;


/**
 * Model tests for Subarray
 */
public class SubarrayTest {
    private final Subarray model = new Subarray();

    /**
     * Model tests for Subarray
     */
    @Test
    public void testSubarray() {
        // TODO: test Subarray
    }

    /**
     * Test the property 'layout'
     */
    @Test
    public void layoutTest() {
        // TODO: test layout
    }

    /**
     * Test the property 'ranges'
     */
    @Test
    public void rangesTest() {
        // TODO: test ranges
    }

}
