/*
 * TileDB Storage Platform API
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 2.2.19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tiledb.cloud.rest_api.model;

import org.junit.Test;


/**
 * Model tests for Subscription
 */
public class SubscriptionTest {
    private final Subscription model = new Subscription();

    /**
     * Model tests for Subscription
     */
    @Test
    public void testSubscription() {
        // TODO: test Subscription
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'ownerNamespaceUuid'
     */
    @Test
    public void ownerNamespaceUuidTest() {
        // TODO: test ownerNamespaceUuid
    }

    /**
     * Test the property 'customerNamespaceUuid'
     */
    @Test
    public void customerNamespaceUuidTest() {
        // TODO: test customerNamespaceUuid
    }

    /**
     * Test the property 'pricing'
     */
    @Test
    public void pricingTest() {
        // TODO: test pricing
    }

}
