/*
 * TileDB Storage Platform API
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 2.17.51
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tiledb.cloud.rest_api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.tiledb.cloud.rest_api.model.TaskGraphLogStatus;
import io.tiledb.cloud.rest_api.model.TaskGraphNodeMetadata;
import io.tiledb.cloud.rest_api.model.TaskGraphType;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TaskGraphLog
 */
public class TaskGraphLogTest {
    private final TaskGraphLog model = new TaskGraphLog();

    /**
     * Model tests for TaskGraphLog
     */
    @Test
    public void testTaskGraphLog() {
        // TODO: test TaskGraphLog
    }

    /**
     * Test the property 'uuid'
     */
    @Test
    public void uuidTest() {
        // TODO: test uuid
    }

    /**
     * Test the property 'namespace'
     */
    @Test
    public void namespaceTest() {
        // TODO: test namespace
    }

    /**
     * Test the property 'createdBy'
     */
    @Test
    public void createdByTest() {
        // TODO: test createdBy
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'startTime'
     */
    @Test
    public void startTimeTest() {
        // TODO: test startTime
    }

    /**
     * Test the property 'endTime'
     */
    @Test
    public void endTimeTest() {
        // TODO: test endTime
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'totalCost'
     */
    @Test
    public void totalCostTest() {
        // TODO: test totalCost
    }

    /**
     * Test the property 'accessCost'
     */
    @Test
    public void accessCostTest() {
        // TODO: test accessCost
    }

    /**
     * Test the property 'egressCost'
     */
    @Test
    public void egressCostTest() {
        // TODO: test egressCost
    }

    /**
     * Test the property 'executionTime'
     */
    @Test
    public void executionTimeTest() {
        // TODO: test executionTime
    }

    /**
     * Test the property 'statusCount'
     */
    @Test
    public void statusCountTest() {
        // TODO: test statusCount
    }

    /**
     * Test the property 'nodes'
     */
    @Test
    public void nodesTest() {
        // TODO: test nodes
    }

    /**
     * Test the property 'taskGraphType'
     */
    @Test
    public void taskGraphTypeTest() {
        // TODO: test taskGraphType
    }

    /**
     * Test the property 'taskGraphId'
     */
    @Test
    public void taskGraphIdTest() {
        // TODO: test taskGraphId
    }

    /**
     * Test the property 'cloudProvider'
     */
    @Test
    public void cloudProviderTest() {
        // TODO: test cloudProvider
    }

    /**
     * Test the property 'cloudRegion'
     */
    @Test
    public void cloudRegionTest() {
        // TODO: test cloudRegion
    }

    /**
     * Test the property 'rootTaskGraphUuid'
     */
    @Test
    public void rootTaskGraphUuidTest() {
        // TODO: test rootTaskGraphUuid
    }

    /**
     * Test the property 'childrenTaskGraphUuids'
     */
    @Test
    public void childrenTaskGraphUuidsTest() {
        // TODO: test childrenTaskGraphUuids
    }

}
