/*
 * TileDB Storage Platform API
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 2.2.19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tiledb.cloud.rest_api.model;

import org.threeten.bp.OffsetDateTime;
import org.junit.Test;


/**
 * Model tests for TaskGraphLog
 */
public class TaskGraphLogTest {
    private final TaskGraphLog model = new TaskGraphLog();

    /**
     * Model tests for TaskGraphLog
     */
    @Test
    public void testTaskGraphLog() {
        // TODO: test TaskGraphLog
    }

    /**
     * Test the property 'uuid'
     */
    @Test
    public void uuidTest() {
        // TODO: test uuid
    }

    /**
     * Test the property 'namespace'
     */
    @Test
    public void namespaceTest() {
        // TODO: test namespace
    }

    /**
     * Test the property 'createdBy'
     */
    @Test
    public void createdByTest() {
        // TODO: test createdBy
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'startTime'
     */
    @Test
    public void startTimeTest() {
        // TODO: test startTime
    }

    /**
     * Test the property 'endTime'
     */
    @Test
    public void endTimeTest() {
        // TODO: test endTime
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'totalCost'
     */
    @Test
    public void totalCostTest() {
        // TODO: test totalCost
    }

    /**
     * Test the property 'accessCost'
     */
    @Test
    public void accessCostTest() {
        // TODO: test accessCost
    }

    /**
     * Test the property 'egressCost'
     */
    @Test
    public void egressCostTest() {
        // TODO: test egressCost
    }

    /**
     * Test the property 'executionTime'
     */
    @Test
    public void executionTimeTest() {
        // TODO: test executionTime
    }

    /**
     * Test the property 'statusCount'
     */
    @Test
    public void statusCountTest() {
        // TODO: test statusCount
    }

    /**
     * Test the property 'nodes'
     */
    @Test
    public void nodesTest() {
        // TODO: test nodes
    }

}
