/*
 * TileDB Storage Platform API
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 2.17.51
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.client.model.InvitationStatus;
import org.openapitools.client.model.InvitationType;
import org.openapitools.client.model.OrganizationRoles;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Invitations to share or collaborate
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-01-21T11:51:21.275554462Z[Etc/UTC]", comments = "Generator version: 7.12.0-SNAPSHOT")
public class Invitation {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_INVITATION_TYPE = "invitation_type";
  @SerializedName(SERIALIZED_NAME_INVITATION_TYPE)
  @javax.annotation.Nullable
  private InvitationType invitationType;

  public static final String SERIALIZED_NAME_OWNER_NAMESPACE_UUID = "owner_namespace_uuid";
  @SerializedName(SERIALIZED_NAME_OWNER_NAMESPACE_UUID)
  @javax.annotation.Nullable
  private String ownerNamespaceUuid;

  public static final String SERIALIZED_NAME_INVITER_UUID = "inviter_uuid";
  @SerializedName(SERIALIZED_NAME_INVITER_UUID)
  @javax.annotation.Nullable
  private String inviterUuid;

  public static final String SERIALIZED_NAME_USER_NAMESPACE_UUID = "user_namespace_uuid";
  @SerializedName(SERIALIZED_NAME_USER_NAMESPACE_UUID)
  @javax.annotation.Nullable
  private String userNamespaceUuid;

  public static final String SERIALIZED_NAME_ORGANIZATION_USER_UUID = "organization_user_uuid";
  @SerializedName(SERIALIZED_NAME_ORGANIZATION_USER_UUID)
  @javax.annotation.Nullable
  private String organizationUserUuid;

  public static final String SERIALIZED_NAME_ORGANIZATION_NAME = "organization_name";
  @SerializedName(SERIALIZED_NAME_ORGANIZATION_NAME)
  @javax.annotation.Nullable
  private String organizationName;

  public static final String SERIALIZED_NAME_ORGANIZATION_ROLE = "organization_role";
  @SerializedName(SERIALIZED_NAME_ORGANIZATION_ROLE)
  @javax.annotation.Nullable
  private OrganizationRoles organizationRole;

  public static final String SERIALIZED_NAME_ORGANIZATION_UUID = "organization_uuid";
  @SerializedName(SERIALIZED_NAME_ORGANIZATION_UUID)
  @javax.annotation.Nullable
  private String organizationUuid;

  public static final String SERIALIZED_NAME_ARRAY_UUID = "array_uuid";
  @SerializedName(SERIALIZED_NAME_ARRAY_UUID)
  @javax.annotation.Nullable
  private String arrayUuid;

  public static final String SERIALIZED_NAME_GROUP_UUID = "group_uuid";
  @SerializedName(SERIALIZED_NAME_GROUP_UUID)
  @javax.annotation.Nullable
  private String groupUuid;

  public static final String SERIALIZED_NAME_ARRAY_NAME = "array_name";
  @SerializedName(SERIALIZED_NAME_ARRAY_NAME)
  @javax.annotation.Nullable
  private String arrayName;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  @javax.annotation.Nullable
  private String email;

  public static final String SERIALIZED_NAME_ACTIONS = "actions";
  @SerializedName(SERIALIZED_NAME_ACTIONS)
  @javax.annotation.Nullable
  private String actions;

  public static final String SERIALIZED_NAME_GROUP_ACTIONS = "group_actions";
  @SerializedName(SERIALIZED_NAME_GROUP_ACTIONS)
  @javax.annotation.Nullable
  private String groupActions;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private InvitationStatus status;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_EXPIRES_AT = "expires_at";
  @SerializedName(SERIALIZED_NAME_EXPIRES_AT)
  @javax.annotation.Nullable
  private OffsetDateTime expiresAt;

  public static final String SERIALIZED_NAME_ACCEPTED_AT = "accepted_at";
  @SerializedName(SERIALIZED_NAME_ACCEPTED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime acceptedAt;

  public static final String SERIALIZED_NAME_NAMESPACE_INVITED = "namespace_invited";
  @SerializedName(SERIALIZED_NAME_NAMESPACE_INVITED)
  @javax.annotation.Nullable
  private String namespaceInvited;

  public Invitation() {
  }

  public Invitation id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Unique ID of invitation added to magic link
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public Invitation invitationType(@javax.annotation.Nullable InvitationType invitationType) {
    this.invitationType = invitationType;
    return this;
  }

  /**
   * Get invitationType
   * @return invitationType
   */
  @javax.annotation.Nullable
  public InvitationType getInvitationType() {
    return invitationType;
  }

  public void setInvitationType(@javax.annotation.Nullable InvitationType invitationType) {
    this.invitationType = invitationType;
  }


  public Invitation ownerNamespaceUuid(@javax.annotation.Nullable String ownerNamespaceUuid) {
    this.ownerNamespaceUuid = ownerNamespaceUuid;
    return this;
  }

  /**
   * Namespace of the owner of the invitation (user or organization)
   * @return ownerNamespaceUuid
   */
  @javax.annotation.Nullable
  public String getOwnerNamespaceUuid() {
    return ownerNamespaceUuid;
  }

  public void setOwnerNamespaceUuid(@javax.annotation.Nullable String ownerNamespaceUuid) {
    this.ownerNamespaceUuid = ownerNamespaceUuid;
  }


  public Invitation inviterUuid(@javax.annotation.Nullable String inviterUuid) {
    this.inviterUuid = inviterUuid;
    return this;
  }

  /**
   * Unique ID of the user that sent the invitation
   * @return inviterUuid
   */
  @javax.annotation.Nullable
  public String getInviterUuid() {
    return inviterUuid;
  }

  public void setInviterUuid(@javax.annotation.Nullable String inviterUuid) {
    this.inviterUuid = inviterUuid;
  }


  public Invitation userNamespaceUuid(@javax.annotation.Nullable String userNamespaceUuid) {
    this.userNamespaceUuid = userNamespaceUuid;
    return this;
  }

  /**
   * Unique ID of the user accepted the invitation
   * @return userNamespaceUuid
   */
  @javax.annotation.Nullable
  public String getUserNamespaceUuid() {
    return userNamespaceUuid;
  }

  public void setUserNamespaceUuid(@javax.annotation.Nullable String userNamespaceUuid) {
    this.userNamespaceUuid = userNamespaceUuid;
  }


  public Invitation organizationUserUuid(@javax.annotation.Nullable String organizationUserUuid) {
    this.organizationUserUuid = organizationUserUuid;
    return this;
  }

  /**
   * Unique ID of the organization user accepted the invitation
   * @return organizationUserUuid
   */
  @javax.annotation.Nullable
  public String getOrganizationUserUuid() {
    return organizationUserUuid;
  }

  public void setOrganizationUserUuid(@javax.annotation.Nullable String organizationUserUuid) {
    this.organizationUserUuid = organizationUserUuid;
  }


  public Invitation organizationName(@javax.annotation.Nullable String organizationName) {
    this.organizationName = organizationName;
    return this;
  }

  /**
   * Name of the organization, does not persist in database
   * @return organizationName
   */
  @javax.annotation.Nullable
  public String getOrganizationName() {
    return organizationName;
  }

  public void setOrganizationName(@javax.annotation.Nullable String organizationName) {
    this.organizationName = organizationName;
  }


  public Invitation organizationRole(@javax.annotation.Nullable OrganizationRoles organizationRole) {
    this.organizationRole = organizationRole;
    return this;
  }

  /**
   * Get organizationRole
   * @return organizationRole
   */
  @javax.annotation.Nullable
  public OrganizationRoles getOrganizationRole() {
    return organizationRole;
  }

  public void setOrganizationRole(@javax.annotation.Nullable OrganizationRoles organizationRole) {
    this.organizationRole = organizationRole;
  }


  public Invitation organizationUuid(@javax.annotation.Nullable String organizationUuid) {
    this.organizationUuid = organizationUuid;
    return this;
  }

  /**
   * Unique ID of the organization whose user(s) accepted the invitation
   * @return organizationUuid
   */
  @javax.annotation.Nullable
  public String getOrganizationUuid() {
    return organizationUuid;
  }

  public void setOrganizationUuid(@javax.annotation.Nullable String organizationUuid) {
    this.organizationUuid = organizationUuid;
  }


  public Invitation arrayUuid(@javax.annotation.Nullable String arrayUuid) {
    this.arrayUuid = arrayUuid;
    return this;
  }

  /**
   * Unique ID of the array
   * @return arrayUuid
   */
  @javax.annotation.Nullable
  public String getArrayUuid() {
    return arrayUuid;
  }

  public void setArrayUuid(@javax.annotation.Nullable String arrayUuid) {
    this.arrayUuid = arrayUuid;
  }


  public Invitation groupUuid(@javax.annotation.Nullable String groupUuid) {
    this.groupUuid = groupUuid;
    return this;
  }

  /**
   * Unique ID of the group
   * @return groupUuid
   */
  @javax.annotation.Nullable
  public String getGroupUuid() {
    return groupUuid;
  }

  public void setGroupUuid(@javax.annotation.Nullable String groupUuid) {
    this.groupUuid = groupUuid;
  }


  public Invitation arrayName(@javax.annotation.Nullable String arrayName) {
    this.arrayName = arrayName;
    return this;
  }

  /**
   * Name of the array, does not persist in database
   * @return arrayName
   */
  @javax.annotation.Nullable
  public String getArrayName() {
    return arrayName;
  }

  public void setArrayName(@javax.annotation.Nullable String arrayName) {
    this.arrayName = arrayName;
  }


  public Invitation email(@javax.annotation.Nullable String email) {
    this.email = email;
    return this;
  }

  /**
   * Email of the individual we send the invitation to
   * @return email
   */
  @javax.annotation.Nullable
  public String getEmail() {
    return email;
  }

  public void setEmail(@javax.annotation.Nullable String email) {
    this.email = email;
  }


  public Invitation actions(@javax.annotation.Nullable String actions) {
    this.actions = actions;
    return this;
  }

  /**
   * A comma separated list of ArrayActions or NamespaceActions
   * @return actions
   */
  @javax.annotation.Nullable
  public String getActions() {
    return actions;
  }

  public void setActions(@javax.annotation.Nullable String actions) {
    this.actions = actions;
  }


  public Invitation groupActions(@javax.annotation.Nullable String groupActions) {
    this.groupActions = groupActions;
    return this;
  }

  /**
   * A comma separated list of GroupActions
   * @return groupActions
   */
  @javax.annotation.Nullable
  public String getGroupActions() {
    return groupActions;
  }

  public void setGroupActions(@javax.annotation.Nullable String groupActions) {
    this.groupActions = groupActions;
  }


  public Invitation status(@javax.annotation.Nullable InvitationStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  public InvitationStatus getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable InvitationStatus status) {
    this.status = status;
  }


  public Invitation createdAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Datetime the invitation was created in UTC
   * @return createdAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public Invitation expiresAt(@javax.annotation.Nullable OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

  /**
   * Datetime the invitation is expected to expire in UTC
   * @return expiresAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getExpiresAt() {
    return expiresAt;
  }

  public void setExpiresAt(@javax.annotation.Nullable OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
  }


  public Invitation acceptedAt(@javax.annotation.Nullable OffsetDateTime acceptedAt) {
    this.acceptedAt = acceptedAt;
    return this;
  }

  /**
   * Datetime the invitation was accepted in UTC
   * @return acceptedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getAcceptedAt() {
    return acceptedAt;
  }

  public void setAcceptedAt(@javax.annotation.Nullable OffsetDateTime acceptedAt) {
    this.acceptedAt = acceptedAt;
  }


  public Invitation namespaceInvited(@javax.annotation.Nullable String namespaceInvited) {
    this.namespaceInvited = namespaceInvited;
    return this;
  }

  /**
   * The namespace invited (user or organization, if it exists in the DB)
   * @return namespaceInvited
   */
  @javax.annotation.Nullable
  public String getNamespaceInvited() {
    return namespaceInvited;
  }

  public void setNamespaceInvited(@javax.annotation.Nullable String namespaceInvited) {
    this.namespaceInvited = namespaceInvited;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Invitation invitation = (Invitation) o;
    return Objects.equals(this.id, invitation.id) &&
        Objects.equals(this.invitationType, invitation.invitationType) &&
        Objects.equals(this.ownerNamespaceUuid, invitation.ownerNamespaceUuid) &&
        Objects.equals(this.inviterUuid, invitation.inviterUuid) &&
        Objects.equals(this.userNamespaceUuid, invitation.userNamespaceUuid) &&
        Objects.equals(this.organizationUserUuid, invitation.organizationUserUuid) &&
        Objects.equals(this.organizationName, invitation.organizationName) &&
        Objects.equals(this.organizationRole, invitation.organizationRole) &&
        Objects.equals(this.organizationUuid, invitation.organizationUuid) &&
        Objects.equals(this.arrayUuid, invitation.arrayUuid) &&
        Objects.equals(this.groupUuid, invitation.groupUuid) &&
        Objects.equals(this.arrayName, invitation.arrayName) &&
        Objects.equals(this.email, invitation.email) &&
        Objects.equals(this.actions, invitation.actions) &&
        Objects.equals(this.groupActions, invitation.groupActions) &&
        Objects.equals(this.status, invitation.status) &&
        Objects.equals(this.createdAt, invitation.createdAt) &&
        Objects.equals(this.expiresAt, invitation.expiresAt) &&
        Objects.equals(this.acceptedAt, invitation.acceptedAt) &&
        Objects.equals(this.namespaceInvited, invitation.namespaceInvited);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, invitationType, ownerNamespaceUuid, inviterUuid, userNamespaceUuid, organizationUserUuid, organizationName, organizationRole, organizationUuid, arrayUuid, groupUuid, arrayName, email, actions, groupActions, status, createdAt, expiresAt, acceptedAt, namespaceInvited);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Invitation {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    invitationType: ").append(toIndentedString(invitationType)).append("\n");
    sb.append("    ownerNamespaceUuid: ").append(toIndentedString(ownerNamespaceUuid)).append("\n");
    sb.append("    inviterUuid: ").append(toIndentedString(inviterUuid)).append("\n");
    sb.append("    userNamespaceUuid: ").append(toIndentedString(userNamespaceUuid)).append("\n");
    sb.append("    organizationUserUuid: ").append(toIndentedString(organizationUserUuid)).append("\n");
    sb.append("    organizationName: ").append(toIndentedString(organizationName)).append("\n");
    sb.append("    organizationRole: ").append(toIndentedString(organizationRole)).append("\n");
    sb.append("    organizationUuid: ").append(toIndentedString(organizationUuid)).append("\n");
    sb.append("    arrayUuid: ").append(toIndentedString(arrayUuid)).append("\n");
    sb.append("    groupUuid: ").append(toIndentedString(groupUuid)).append("\n");
    sb.append("    arrayName: ").append(toIndentedString(arrayName)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("    groupActions: ").append(toIndentedString(groupActions)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    acceptedAt: ").append(toIndentedString(acceptedAt)).append("\n");
    sb.append("    namespaceInvited: ").append(toIndentedString(namespaceInvited)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("invitation_type");
    openapiFields.add("owner_namespace_uuid");
    openapiFields.add("inviter_uuid");
    openapiFields.add("user_namespace_uuid");
    openapiFields.add("organization_user_uuid");
    openapiFields.add("organization_name");
    openapiFields.add("organization_role");
    openapiFields.add("organization_uuid");
    openapiFields.add("array_uuid");
    openapiFields.add("group_uuid");
    openapiFields.add("array_name");
    openapiFields.add("email");
    openapiFields.add("actions");
    openapiFields.add("group_actions");
    openapiFields.add("status");
    openapiFields.add("created_at");
    openapiFields.add("expires_at");
    openapiFields.add("accepted_at");
    openapiFields.add("namespace_invited");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Invitation
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Invitation.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Invitation is not found in the empty JSON string", Invitation.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Invitation.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Invitation` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      // validate the optional field `invitation_type`
      if (jsonObj.get("invitation_type") != null && !jsonObj.get("invitation_type").isJsonNull()) {
        InvitationType.validateJsonElement(jsonObj.get("invitation_type"));
      }
      if ((jsonObj.get("owner_namespace_uuid") != null && !jsonObj.get("owner_namespace_uuid").isJsonNull()) && !jsonObj.get("owner_namespace_uuid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `owner_namespace_uuid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("owner_namespace_uuid").toString()));
      }
      if ((jsonObj.get("inviter_uuid") != null && !jsonObj.get("inviter_uuid").isJsonNull()) && !jsonObj.get("inviter_uuid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `inviter_uuid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("inviter_uuid").toString()));
      }
      if ((jsonObj.get("user_namespace_uuid") != null && !jsonObj.get("user_namespace_uuid").isJsonNull()) && !jsonObj.get("user_namespace_uuid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `user_namespace_uuid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("user_namespace_uuid").toString()));
      }
      if ((jsonObj.get("organization_user_uuid") != null && !jsonObj.get("organization_user_uuid").isJsonNull()) && !jsonObj.get("organization_user_uuid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `organization_user_uuid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("organization_user_uuid").toString()));
      }
      if ((jsonObj.get("organization_name") != null && !jsonObj.get("organization_name").isJsonNull()) && !jsonObj.get("organization_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `organization_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("organization_name").toString()));
      }
      // validate the optional field `organization_role`
      if (jsonObj.get("organization_role") != null && !jsonObj.get("organization_role").isJsonNull()) {
        OrganizationRoles.validateJsonElement(jsonObj.get("organization_role"));
      }
      if ((jsonObj.get("organization_uuid") != null && !jsonObj.get("organization_uuid").isJsonNull()) && !jsonObj.get("organization_uuid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `organization_uuid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("organization_uuid").toString()));
      }
      if ((jsonObj.get("array_uuid") != null && !jsonObj.get("array_uuid").isJsonNull()) && !jsonObj.get("array_uuid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `array_uuid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("array_uuid").toString()));
      }
      if ((jsonObj.get("group_uuid") != null && !jsonObj.get("group_uuid").isJsonNull()) && !jsonObj.get("group_uuid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `group_uuid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("group_uuid").toString()));
      }
      if ((jsonObj.get("array_name") != null && !jsonObj.get("array_name").isJsonNull()) && !jsonObj.get("array_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `array_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("array_name").toString()));
      }
      if ((jsonObj.get("email") != null && !jsonObj.get("email").isJsonNull()) && !jsonObj.get("email").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `email` to be a primitive type in the JSON string but got `%s`", jsonObj.get("email").toString()));
      }
      if ((jsonObj.get("actions") != null && !jsonObj.get("actions").isJsonNull()) && !jsonObj.get("actions").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `actions` to be a primitive type in the JSON string but got `%s`", jsonObj.get("actions").toString()));
      }
      if ((jsonObj.get("group_actions") != null && !jsonObj.get("group_actions").isJsonNull()) && !jsonObj.get("group_actions").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `group_actions` to be a primitive type in the JSON string but got `%s`", jsonObj.get("group_actions").toString()));
      }
      // validate the optional field `status`
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) {
        InvitationStatus.validateJsonElement(jsonObj.get("status"));
      }
      if ((jsonObj.get("namespace_invited") != null && !jsonObj.get("namespace_invited").isJsonNull()) && !jsonObj.get("namespace_invited").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `namespace_invited` to be a primitive type in the JSON string but got `%s`", jsonObj.get("namespace_invited").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Invitation.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Invitation' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Invitation> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Invitation.class));

       return (TypeAdapter<T>) new TypeAdapter<Invitation>() {
           @Override
           public void write(JsonWriter out, Invitation value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Invitation read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Invitation given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Invitation
   * @throws IOException if the JSON string is invalid with respect to Invitation
   */
  public static Invitation fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Invitation.class);
  }

  /**
   * Convert an instance of Invitation to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

