/*
 * TileDB Storage Platform API
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 2.17.51
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.SubarrayPartitioner;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * state for reads
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-01-21T11:51:21.275554462Z[Etc/UTC]", comments = "Generator version: 7.12.0-SNAPSHOT")
public class ReadState {
  public static final String SERIALIZED_NAME_INITIALIZED = "initialized";
  @SerializedName(SERIALIZED_NAME_INITIALIZED)
  @javax.annotation.Nullable
  private Boolean initialized;

  public static final String SERIALIZED_NAME_OVERFLOWED = "overflowed";
  @SerializedName(SERIALIZED_NAME_OVERFLOWED)
  @javax.annotation.Nullable
  private Boolean overflowed;

  public static final String SERIALIZED_NAME_UNSPLITTABLE = "unsplittable";
  @SerializedName(SERIALIZED_NAME_UNSPLITTABLE)
  @javax.annotation.Nullable
  private Boolean unsplittable;

  public static final String SERIALIZED_NAME_SUBARRAY_PARTITIONER = "subarrayPartitioner";
  @SerializedName(SERIALIZED_NAME_SUBARRAY_PARTITIONER)
  @javax.annotation.Nullable
  private SubarrayPartitioner subarrayPartitioner;

  public ReadState() {
  }

  public ReadState initialized(@javax.annotation.Nullable Boolean initialized) {
    this.initialized = initialized;
    return this;
  }

  /**
   * True if the reader has been initialized.
   * @return initialized
   */
  @javax.annotation.Nullable
  public Boolean getInitialized() {
    return initialized;
  }

  public void setInitialized(@javax.annotation.Nullable Boolean initialized) {
    this.initialized = initialized;
  }


  public ReadState overflowed(@javax.annotation.Nullable Boolean overflowed) {
    this.overflowed = overflowed;
    return this;
  }

  /**
   * True if the query produced results that could not fit in some buffer.
   * @return overflowed
   */
  @javax.annotation.Nullable
  public Boolean getOverflowed() {
    return overflowed;
  }

  public void setOverflowed(@javax.annotation.Nullable Boolean overflowed) {
    this.overflowed = overflowed;
  }


  public ReadState unsplittable(@javax.annotation.Nullable Boolean unsplittable) {
    this.unsplittable = unsplittable;
    return this;
  }

  /**
   * True if the current subarray partition is unsplittable.
   * @return unsplittable
   */
  @javax.annotation.Nullable
  public Boolean getUnsplittable() {
    return unsplittable;
  }

  public void setUnsplittable(@javax.annotation.Nullable Boolean unsplittable) {
    this.unsplittable = unsplittable;
  }


  public ReadState subarrayPartitioner(@javax.annotation.Nullable SubarrayPartitioner subarrayPartitioner) {
    this.subarrayPartitioner = subarrayPartitioner;
    return this;
  }

  /**
   * Get subarrayPartitioner
   * @return subarrayPartitioner
   */
  @javax.annotation.Nullable
  public SubarrayPartitioner getSubarrayPartitioner() {
    return subarrayPartitioner;
  }

  public void setSubarrayPartitioner(@javax.annotation.Nullable SubarrayPartitioner subarrayPartitioner) {
    this.subarrayPartitioner = subarrayPartitioner;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReadState readState = (ReadState) o;
    return Objects.equals(this.initialized, readState.initialized) &&
        Objects.equals(this.overflowed, readState.overflowed) &&
        Objects.equals(this.unsplittable, readState.unsplittable) &&
        Objects.equals(this.subarrayPartitioner, readState.subarrayPartitioner);
  }

  @Override
  public int hashCode() {
    return Objects.hash(initialized, overflowed, unsplittable, subarrayPartitioner);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReadState {\n");
    sb.append("    initialized: ").append(toIndentedString(initialized)).append("\n");
    sb.append("    overflowed: ").append(toIndentedString(overflowed)).append("\n");
    sb.append("    unsplittable: ").append(toIndentedString(unsplittable)).append("\n");
    sb.append("    subarrayPartitioner: ").append(toIndentedString(subarrayPartitioner)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("initialized");
    openapiFields.add("overflowed");
    openapiFields.add("unsplittable");
    openapiFields.add("subarrayPartitioner");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ReadState
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ReadState.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ReadState is not found in the empty JSON string", ReadState.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ReadState.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ReadState` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `subarrayPartitioner`
      if (jsonObj.get("subarrayPartitioner") != null && !jsonObj.get("subarrayPartitioner").isJsonNull()) {
        SubarrayPartitioner.validateJsonElement(jsonObj.get("subarrayPartitioner"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ReadState.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ReadState' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ReadState> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ReadState.class));

       return (TypeAdapter<T>) new TypeAdapter<ReadState>() {
           @Override
           public void write(JsonWriter out, ReadState value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ReadState read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ReadState given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ReadState
   * @throws IOException if the JSON string is invalid with respect to ReadState
   */
  public static ReadState fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ReadState.class);
  }

  /**
   * Convert an instance of ReadState to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

