/*
 * Tiledb Storage Platform API
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tiledb.cloud.rest_api.v2.model;

import java.util.Objects;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;

import io.tiledb.cloud.rest_api.v2.JSON;

/**
 * Updates the contents group
 */
@ApiModel(description = "Updates the contents group")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-02T18:54:48.746612+03:00[Europe/Athens]")
public class GroupContentsChangesRequest {
  public static final String SERIALIZED_NAME_CONFIG = "config";
  @SerializedName(SERIALIZED_NAME_CONFIG)
  private TileDBConfig config;

  public static final String SERIALIZED_NAME_GROUP_CHANGES = "group_changes";
  @SerializedName(SERIALIZED_NAME_GROUP_CHANGES)
  private GroupContentsChangesRequestGroupChanges groupChanges;

  public GroupContentsChangesRequest() { 
  }

  public GroupContentsChangesRequest config(TileDBConfig config) {
    
    this.config = config;
    return this;
  }

   /**
   * Get config
   * @return config
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public TileDBConfig getConfig() {
    return config;
  }


  public void setConfig(TileDBConfig config) {
    this.config = config;
  }


  public GroupContentsChangesRequest groupChanges(GroupContentsChangesRequestGroupChanges groupChanges) {
    
    this.groupChanges = groupChanges;
    return this;
  }

   /**
   * Get groupChanges
   * @return groupChanges
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GroupContentsChangesRequestGroupChanges getGroupChanges() {
    return groupChanges;
  }


  public void setGroupChanges(GroupContentsChangesRequestGroupChanges groupChanges) {
    this.groupChanges = groupChanges;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   */
  public GroupContentsChangesRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GroupContentsChangesRequest groupContentsChangesRequest = (GroupContentsChangesRequest) o;
    return Objects.equals(this.config, groupContentsChangesRequest.config) &&
        Objects.equals(this.groupChanges, groupContentsChangesRequest.groupChanges)&&
        Objects.equals(this.additionalProperties, groupContentsChangesRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(config, groupChanges, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GroupContentsChangesRequest {\n");
    sb.append("    config: ").append(toIndentedString(config)).append("\n");
    sb.append("    groupChanges: ").append(toIndentedString(groupChanges)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("config");
    openapiFields.add("group_changes");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to GroupContentsChangesRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (GroupContentsChangesRequest.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in GroupContentsChangesRequest is not found in the empty JSON string", GroupContentsChangesRequest.openapiRequiredFields.toString()));
        }
      }
      // validate the optional field `config`
      if (jsonObj.getAsJsonObject("config") != null) {
        TileDBConfig.validateJsonObject(jsonObj.getAsJsonObject("config"));
      }
      // validate the optional field `group_changes`
      if (jsonObj.getAsJsonObject("group_changes") != null) {
        GroupContentsChangesRequestGroupChanges.validateJsonObject(jsonObj.getAsJsonObject("group_changes"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GroupContentsChangesRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GroupContentsChangesRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GroupContentsChangesRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GroupContentsChangesRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<GroupContentsChangesRequest>() {
           @Override
           public void write(JsonWriter out, GroupContentsChangesRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public GroupContentsChangesRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             GroupContentsChangesRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else { // non-primitive type
                   instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of GroupContentsChangesRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of GroupContentsChangesRequest
  * @throws IOException if the JSON string is invalid with respect to GroupContentsChangesRequest
  */
  public static GroupContentsChangesRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GroupContentsChangesRequest.class);
  }

 /**
  * Convert an instance of GroupContentsChangesRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

