/*
 * TileDB Storage Platform API
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 2.2.19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ArrayTaskLog
 */
public class ArrayTaskLogTest {
    private final ArrayTaskLog model = new ArrayTaskLog();

    /**
     * Model tests for ArrayTaskLog
     */
    @Test
    public void testArrayTaskLog() {
        // TODO: test ArrayTaskLog
    }

    /**
     * Test the property 'arrayTaskId'
     */
    @Test
    public void arrayTaskIdTest() {
        // TODO: test arrayTaskId
    }

    /**
     * Test the property 'logs'
     */
    @Test
    public void logsTest() {
        // TODO: test logs
    }

}
