/*
 * TileDB Storage Platform API
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 2.2.19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.NamespaceActions;
import org.openapitools.client.model.OrganizationRoles;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InvitationOrganizationJoinEmail
 */
public class InvitationOrganizationJoinEmailTest {
    private final InvitationOrganizationJoinEmail model = new InvitationOrganizationJoinEmail();

    /**
     * Model tests for InvitationOrganizationJoinEmail
     */
    @Test
    public void testInvitationOrganizationJoinEmail() {
        // TODO: test InvitationOrganizationJoinEmail
    }

    /**
     * Test the property 'actions'
     */
    @Test
    public void actionsTest() {
        // TODO: test actions
    }

    /**
     * Test the property 'organizationRole'
     */
    @Test
    public void organizationRoleTest() {
        // TODO: test organizationRole
    }

    /**
     * Test the property 'inviteeEmail'
     */
    @Test
    public void inviteeEmailTest() {
        // TODO: test inviteeEmail
    }

}
