/*
 * TileDB Storage Platform API
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 2.2.19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.Datatype;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SubarrayRanges
 */
public class SubarrayRangesTest {
    private final SubarrayRanges model = new SubarrayRanges();

    /**
     * Model tests for SubarrayRanges
     */
    @Test
    public void testSubarrayRanges() {
        // TODO: test SubarrayRanges
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'hasDefaultRange'
     */
    @Test
    public void hasDefaultRangeTest() {
        // TODO: test hasDefaultRange
    }

    /**
     * Test the property 'buffer'
     */
    @Test
    public void bufferTest() {
        // TODO: test buffer
    }

}
