/*
 * TileDB Storage Platform API
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 2.2.19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ArrayTask;
import org.openapitools.client.model.ArrayTaskStatus;
import org.openapitools.client.model.TaskGraphLogRunLocation;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TaskGraphNodeMetadata
 */
public class TaskGraphNodeMetadataTest {
    private final TaskGraphNodeMetadata model = new TaskGraphNodeMetadata();

    /**
     * Model tests for TaskGraphNodeMetadata
     */
    @Test
    public void testTaskGraphNodeMetadata() {
        // TODO: test TaskGraphNodeMetadata
    }

    /**
     * Test the property 'clientNodeUuid'
     */
    @Test
    public void clientNodeUuidTest() {
        // TODO: test clientNodeUuid
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'dependsOn'
     */
    @Test
    public void dependsOnTest() {
        // TODO: test dependsOn
    }

    /**
     * Test the property 'runLocation'
     */
    @Test
    public void runLocationTest() {
        // TODO: test runLocation
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'executions'
     */
    @Test
    public void executionsTest() {
        // TODO: test executions
    }

}
