/*
 * TileDB Storage Platform API
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 2.17.51
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tiledb.cloud.rest_api.api;

import io.tiledb.cloud.rest_api.ApiException;
import io.tiledb.cloud.rest_api.model.ArrayTaskBrowserSidebar;
import io.tiledb.cloud.rest_api.model.Error;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ArrayTasksApi
 */
@Disabled
public class ArrayTasksApiTest {

    private final ArrayTasksApi api = new ArrayTasksApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getArrayTasksSidebarTest() throws ApiException {
        Integer start = null;
        Integer end = null;
        ArrayTaskBrowserSidebar response = api.getArrayTasksSidebar(start, end);
        // TODO: test validations
    }

}
