/*
 * Specification file for tiledb-server v4 API
 * This spec is exposed to the public under /v4 route group
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@tiledb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tiledb.cloud.v4.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.tiledb.cloud.v4.model.WorkspaceRole;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.tiledb.cloud.v4.JSON;

/**
 * InvitationWorkspace
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class InvitationWorkspace {
  public static final String SERIALIZED_NAME_WORKSPACE_ID = "workspace_id";
  @SerializedName(SERIALIZED_NAME_WORKSPACE_ID)
  @javax.annotation.Nonnull
  private String workspaceId;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_IMAGE_ID = "image_id";
  @SerializedName(SERIALIZED_NAME_IMAGE_ID)
  @javax.annotation.Nullable
  private String imageId;

  public static final String SERIALIZED_NAME_PROSPECTIVE_ROLE = "prospective_role";
  @SerializedName(SERIALIZED_NAME_PROSPECTIVE_ROLE)
  @javax.annotation.Nonnull
  private WorkspaceRole prospectiveRole;

  public InvitationWorkspace() {
  }

  public InvitationWorkspace workspaceId(@javax.annotation.Nonnull String workspaceId) {
    this.workspaceId = workspaceId;
    return this;
  }

  /**
   * The workspace&#39;s ID
   * @return workspaceId
   */
  @javax.annotation.Nonnull
  public String getWorkspaceId() {
    return workspaceId;
  }

  public void setWorkspaceId(@javax.annotation.Nonnull String workspaceId) {
    this.workspaceId = workspaceId;
  }


  public InvitationWorkspace name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * The workspace&#39;s name
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public InvitationWorkspace description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * The workspace&#39;s description
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public InvitationWorkspace imageId(@javax.annotation.Nullable String imageId) {
    this.imageId = imageId;
    return this;
  }

  /**
   * The image&#39;s ID
   * @return imageId
   */
  @javax.annotation.Nullable
  public String getImageId() {
    return imageId;
  }

  public void setImageId(@javax.annotation.Nullable String imageId) {
    this.imageId = imageId;
  }


  public InvitationWorkspace prospectiveRole(@javax.annotation.Nonnull WorkspaceRole prospectiveRole) {
    this.prospectiveRole = prospectiveRole;
    return this;
  }

  /**
   * Get prospectiveRole
   * @return prospectiveRole
   */
  @javax.annotation.Nonnull
  public WorkspaceRole getProspectiveRole() {
    return prospectiveRole;
  }

  public void setProspectiveRole(@javax.annotation.Nonnull WorkspaceRole prospectiveRole) {
    this.prospectiveRole = prospectiveRole;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InvitationWorkspace invitationWorkspace = (InvitationWorkspace) o;
    return Objects.equals(this.workspaceId, invitationWorkspace.workspaceId) &&
        Objects.equals(this.name, invitationWorkspace.name) &&
        Objects.equals(this.description, invitationWorkspace.description) &&
        Objects.equals(this.imageId, invitationWorkspace.imageId) &&
        Objects.equals(this.prospectiveRole, invitationWorkspace.prospectiveRole);
  }

  @Override
  public int hashCode() {
    return Objects.hash(workspaceId, name, description, imageId, prospectiveRole);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InvitationWorkspace {\n");
    sb.append("    workspaceId: ").append(toIndentedString(workspaceId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    imageId: ").append(toIndentedString(imageId)).append("\n");
    sb.append("    prospectiveRole: ").append(toIndentedString(prospectiveRole)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("workspace_id");
    openapiFields.add("name");
    openapiFields.add("description");
    openapiFields.add("image_id");
    openapiFields.add("prospective_role");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("workspace_id");
    openapiRequiredFields.add("name");
    openapiRequiredFields.add("prospective_role");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to InvitationWorkspace
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!InvitationWorkspace.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in InvitationWorkspace is not found in the empty JSON string", InvitationWorkspace.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!InvitationWorkspace.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `InvitationWorkspace` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : InvitationWorkspace.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("workspace_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `workspace_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("workspace_id").toString()));
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if ((jsonObj.get("image_id") != null && !jsonObj.get("image_id").isJsonNull()) && !jsonObj.get("image_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `image_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("image_id").toString()));
      }
      // validate the required field `prospective_role`
      WorkspaceRole.validateJsonElement(jsonObj.get("prospective_role"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!InvitationWorkspace.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'InvitationWorkspace' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<InvitationWorkspace> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(InvitationWorkspace.class));

       return (TypeAdapter<T>) new TypeAdapter<InvitationWorkspace>() {
           @Override
           public void write(JsonWriter out, InvitationWorkspace value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public InvitationWorkspace read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of InvitationWorkspace given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of InvitationWorkspace
   * @throws IOException if the JSON string is invalid with respect to InvitationWorkspace
   */
  public static InvitationWorkspace fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, InvitationWorkspace.class);
  }

  /**
   * Convert an instance of InvitationWorkspace to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

