/*
 * Specification file for tiledb-server v4 API
 * This spec is exposed to the public under /v4 route group
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@tiledb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tiledb.cloud.v4.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.tiledb.cloud.v4.model.InvitationWorkspace;
import io.tiledb.cloud.v4.model.InvitingUser;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.tiledb.cloud.v4.JSON;

/**
 * The invitation object
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class Invitation {
  public static final String SERIALIZED_NAME_INVITATION_ID = "invitation_id";
  @SerializedName(SERIALIZED_NAME_INVITATION_ID)
  @javax.annotation.Nonnull
  private String invitationId;

  public static final String SERIALIZED_NAME_INVITEE_EMAIL = "invitee_email";
  @SerializedName(SERIALIZED_NAME_INVITEE_EMAIL)
  @javax.annotation.Nonnull
  private String inviteeEmail;

  public static final String SERIALIZED_NAME_CREATED_BY = "created_by";
  @SerializedName(SERIALIZED_NAME_CREATED_BY)
  @javax.annotation.Nonnull
  private InvitingUser createdBy;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_WORKSPACE_INVITATION = "workspace_invitation";
  @SerializedName(SERIALIZED_NAME_WORKSPACE_INVITATION)
  @javax.annotation.Nullable
  private InvitationWorkspace workspaceInvitation;

  public Invitation() {
  }

  public Invitation invitationId(@javax.annotation.Nonnull String invitationId) {
    this.invitationId = invitationId;
    return this;
  }

  /**
   * The invitation&#39;s ID
   * @return invitationId
   */
  @javax.annotation.Nonnull
  public String getInvitationId() {
    return invitationId;
  }

  public void setInvitationId(@javax.annotation.Nonnull String invitationId) {
    this.invitationId = invitationId;
  }


  public Invitation inviteeEmail(@javax.annotation.Nonnull String inviteeEmail) {
    this.inviteeEmail = inviteeEmail;
    return this;
  }

  /**
   * The invited user&#39;s email address
   * @return inviteeEmail
   */
  @javax.annotation.Nonnull
  public String getInviteeEmail() {
    return inviteeEmail;
  }

  public void setInviteeEmail(@javax.annotation.Nonnull String inviteeEmail) {
    this.inviteeEmail = inviteeEmail;
  }


  public Invitation createdBy(@javax.annotation.Nonnull InvitingUser createdBy) {
    this.createdBy = createdBy;
    return this;
  }

  /**
   * Get createdBy
   * @return createdBy
   */
  @javax.annotation.Nonnull
  public InvitingUser getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(@javax.annotation.Nonnull InvitingUser createdBy) {
    this.createdBy = createdBy;
  }


  public Invitation createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * The date and time the invitation was created
   * @return createdAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public Invitation workspaceInvitation(@javax.annotation.Nullable InvitationWorkspace workspaceInvitation) {
    this.workspaceInvitation = workspaceInvitation;
    return this;
  }

  /**
   * Get workspaceInvitation
   * @return workspaceInvitation
   */
  @javax.annotation.Nullable
  public InvitationWorkspace getWorkspaceInvitation() {
    return workspaceInvitation;
  }

  public void setWorkspaceInvitation(@javax.annotation.Nullable InvitationWorkspace workspaceInvitation) {
    this.workspaceInvitation = workspaceInvitation;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Invitation invitation = (Invitation) o;
    return Objects.equals(this.invitationId, invitation.invitationId) &&
        Objects.equals(this.inviteeEmail, invitation.inviteeEmail) &&
        Objects.equals(this.createdBy, invitation.createdBy) &&
        Objects.equals(this.createdAt, invitation.createdAt) &&
        Objects.equals(this.workspaceInvitation, invitation.workspaceInvitation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(invitationId, inviteeEmail, createdBy, createdAt, workspaceInvitation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Invitation {\n");
    sb.append("    invitationId: ").append(toIndentedString(invitationId)).append("\n");
    sb.append("    inviteeEmail: ").append(toIndentedString(inviteeEmail)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    workspaceInvitation: ").append(toIndentedString(workspaceInvitation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("invitation_id");
    openapiFields.add("invitee_email");
    openapiFields.add("created_by");
    openapiFields.add("created_at");
    openapiFields.add("workspace_invitation");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("invitation_id");
    openapiRequiredFields.add("invitee_email");
    openapiRequiredFields.add("created_by");
    openapiRequiredFields.add("created_at");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Invitation
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Invitation.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Invitation is not found in the empty JSON string", Invitation.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Invitation.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Invitation` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Invitation.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("invitation_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `invitation_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("invitation_id").toString()));
      }
      if (!jsonObj.get("invitee_email").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `invitee_email` to be a primitive type in the JSON string but got `%s`", jsonObj.get("invitee_email").toString()));
      }
      // validate the required field `created_by`
      InvitingUser.validateJsonElement(jsonObj.get("created_by"));
      // validate the optional field `workspace_invitation`
      if (jsonObj.get("workspace_invitation") != null && !jsonObj.get("workspace_invitation").isJsonNull()) {
        InvitationWorkspace.validateJsonElement(jsonObj.get("workspace_invitation"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Invitation.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Invitation' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Invitation> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Invitation.class));

       return (TypeAdapter<T>) new TypeAdapter<Invitation>() {
           @Override
           public void write(JsonWriter out, Invitation value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Invitation read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Invitation given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Invitation
   * @throws IOException if the JSON string is invalid with respect to Invitation
   */
  public static Invitation fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Invitation.class);
  }

  /**
   * Convert an instance of Invitation to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

